name: CISample

on: [push]
env:
  APP_NAME: Test Python
jobs:
  lintjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: install req
      run: pip install --quiet --requirememt ../../requirements.txt
