name: CIMain

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  OnMain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        env:
          DOCKER_USER: ${{secrets.DOCKER_ID}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build and Push the Python Image to docker Hub
        run: docker build . --tag vamc/python:$(date +%s)
      - name: Push the Image to my Public Repo
        run: docker push ${{secrets.DOCKER_ID}}/learnk8s