name: CIMain

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  OnMain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        env:
          DOCKER_USER: ${{secrets.DOCKER_ID}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
          TAG: $(date +%s)
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Python webapp Image
        run: docker build . --tag vamc1715/learnk8s:$TAG
      - name: docker list
        run: docker images
      - name: Push the Image to my Public Repo
        run: docker push vamc1715/learnk8s:$TAG