name: CIMain

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  OnMain:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ date +%s }}
    steps:
      - name: Fetch date
        id: datetag
        run: echo $(date +s%)
      - name: check the value
        run: echo ${{ steps.datetag.output }}
      # - uses: actions/checkout@v2
      # - name: Login to Docker
      #   env:
      #     DOCKER_USER: ${{secrets.DOCKER_ID}}
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
      #   run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # - name: Build Python webapp Image
      #   run: docker build . --tag vamc1715/learnk8s:${{ steps.datetag.output}}
      # - name: docker list
      #   run: docker images
      # - name: Push the Image to my Public Repo
      #   run: docker push vamc1715/learnk8s:$TAG