on:
  release:
    types: [published]

jobs:
  Deploy:
  runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps: 
      - name: Initiate Deploy
        run: echo "Deployment Initiated"
      - name: Deploy
        run: echo "Code Deployment after Merge is successful"